### ISSUE TITLE
Add guidelines for advisors

### ISSUE THREAD

**Issue by OrkoHunter** [kossiitkgp/docs#10]
Hey all!

Pranit has written a beautiful document about advisors. Our [Guidelines for Advisors](https://github.com/kossiitkgp/docs/blob/master/community/governance.md#guidelines-for-advisors--) section in governance doc is empty.

@pranitbauva1997 Please send a Pull Request when you get the time. Meanwhile, you can copy-paste the content over here.

**Comment by OrkoHunter** [comment]
Hey @pranitbauva1997 ! Feeling the pain in finding the time? :D

**Comment by pranitbauva1997** [comment]
Fixed in #13
