### ISSUE TITLE
Removing the role of executive members from koss documentation

### ISSUE THREAD

**Issue by rava-dosa** [kossiitkgp/docs#15]
### Why
I personally feel that due to kgp culture and influence from different societies people take this the wrong way. And it brings unneeded toxicity to KoSS. This executive batch was the first time when executive members were made executive member:-
1. Some chose not to become executive heads but they had real emotional and physical involvement . 
2. Executive heads were made based on the group understanding of people who can lead KoSS. 
In some batch it was made because some people weren't particularly active but they had some involvement. 
### Pros of having this division. 
1. One of the major pro is to take fast decision more people tends to slow down decision making process. 
2. Small group of people leads to better bonding. And bonding leads to more intimate discussion. And I think intimate discussion leads to layered ideas which stands a better chance for taking the test of time and culture. 
### Cons of having this division.
1. One of the major cons I saw was, people referring to documentation as a proof to justify even some weird steps they took. Documentation were meant for a "guideline" and not as a rules. It never should taken word by word. "Words" are ambiguous in the sense they evoke different emotion. Some word might be insulting to someone and the same word will be quite okay for some other person. "Executive member are not just resources and they are complete human being.". And taking someone's ability to be a considerable part of judgement will somehow remove their interest as well, might hurt someone and discourage them to contribute. 
2. Human Judgement  and human being:- They are always biased. They are based on perception. Not that we should just remove human judgement which will be more disastrous. Most of us are in the age group of 18-23. And most of us are rapidly evolving in every terms possible. I am sure that the people who decided that "these x members will the executive heads" have grown enough to think that if they took this decision 1 year later their decision must be different. So none of us have enough wisdom to select heads. And it will always to devastating. And even the people we are selecting their priorities will change continuously and they will grow as fast as everyone else. So making an executive heads has two major flaws, we might select wrong people, and second the might become disinterested and grow apart from what koss as a group wants to do and they will be pressured to do that(I know no one presures, but giving the title(Executive heads) kind of entitles the person to perform. It's morning and I am not able to frame it any better sorry).

### Can we do better 
So I suggest three things :-
0. Remove this division.
1. Proof of work, inactivity and singular responsibility :- 
a. Singular responsibility :- Recently I saw a great thing that one or two people taking responsibility for the whole events. Which is really great. It leads to better decision making. Eventwise resposibility distribution based on hall or department or friendship or availability can be better way to move forward. 
b. Proof of work and inactivity:- We should use github commits and markdown to manage the whole events. Every person including executive and core team members should add his contribution to that event. So after two three events the whole team knows which ctm and executives are inactive. So here advisors can take the role and talk to them not just in terms of koss but talk to them as a human(and your juniors) if they are physically and mentally good. We can have some inactive members list(not sure how good is that).

**Comment by OrkoHunter** [comment]
Hi @rava-dosa ! I am sorry to see your post not getting enough traction. Anyway, I support your understanding and quite like the unique way to measure "singular responsibility". Definitely go ahead with this.

I have a couple of small notes in mind -
1. Generalisation: It is going to be hard for us to generalise systems. Executive Member and Head model might be very elegant for some batch and might create disaster for the next. So, we should understand that the problems _might be_ very specific to the current batch and not all the batches in general.
2. Don't forget that a lot of bonding and "uninterested members" problem is solved by fixing the way we hire and onboard new members.

**Comment by pranitbauva1997** [comment]
I too feel a position like "Executive Members" doesn't make much sense. There's always a chance that in some batch someone might try to show some authority because of his/her title while the other would think it wasn't important because of his/her title.

**Comment by pranitbauva1997** [comment]
@rava-dosa I think we are meeting this Thursday amongst advisors to discuss what we finally want to do. Let me know if there is any change in plans.
