### ISSUE TITLE
Overlapping text in webpage

### ISSUE THREAD

**Issue by shruti170901** [kossiitkgp/docs#20]
## Issue found in 
https://beta.kossiitkgp.org/docs/community/governance-review-week/

## Description of issue found
The sidebar is shifted from its place as a result of which text is overlapping
![Screenshot ](https://user-images.githubusercontent.com/58871601/82416748-2f731880-9a98-11ea-90f8-575f24930fa5.png)

## Specifications
O.S. : Windows 10
Browser : Chrome

**Comment by yashrsharma44** [comment]
@shruti170901 Thanks for opening the issue! If you want, you can send in bug fix 🙂
