### ISSUE TITLE
Adds docs related to FAQs asked on our facebook page

### ISSUE THREAD

**Issue by rakaar** [kossiitkgp/docs#33]
- [x] When do the selections happen?

- [x] What is the criteria for getting selected?

- [x] Do we take in 2nd years/ Mtechs/PhDs?

**Comment by OrkoHunter** [comment]
I think the selections doc answers these three questions.

**Comment by rakaar** [comment]
@OrkoHunter 
Ya found [this](https://github.com/kossiitkgp/docs/blob/b9ef16aad2729a7dffdb5482de7a1ad96ac772e1/events/freshers-selection.md) and [this](https://github.com/kossiitkgp/docs/blob/master/community/governance.md#the-policy-of-koss-membership), thanks! 
This answers the first 2 questions
But this doesn't mention explicitly about MTech or PhDs, do you think we should add it separately?

**Comment by xypnox** [comment]
Also, we need to update them on the website, currently I can navigate to only the Governance Doc. And it will not be obvious for someone looking for the criteria for KOSS membership to visit the governance page. 

Although a case can be made that the person who didn't look enough wasn't curious to begin with, however, I think we should add some details about the pages in a sentence or so in the index: https://beta.kossiitkgp.org/docs/.

**Comment by OrkoHunter** [comment]
> But this doesn't mention explicitly about MTech or PhDs, do you think we should add it separately?

Yeah sure. We don't need to put this on top of the page, to avoid unnecessary criticism.

It's a grey area. We have worked with MTechs and PhDs in the past and will always do so. But it will be difficult for them to be an official "member". We as members have to do a lot more things which MTechs and PhDs might not be willing to do or won't have the time to do (attending all the meetings being, handling logistics of the event, etc.) But at the same time, they can be one of our speakers in any event.

**Comment by rakaar** [comment]
fixed by #34
