### ISSUE TITLE
Update recruitment.md on the intake of people 

### ISSUE THREAD

**Issue by iamananya** [kossiitkgp/docs#48]
* Specify the intake of people to be limited and serious ones.

**Comment by proffapt** [comment]
https://github.com/kossiitkgp/docs/blob/2f2fb0c6decc63ddb86a9f893a80ade8af085f34/events/freshers-selection.md?plain=1#L108

Ig that's enough to be mentioned?

cc: @rajivharlalka @likhith2003

**Comment by rajivharlalka** [comment]
Yeps

**Comment by proffapt** [comment]
> Yeps

Then shall we close this issue and corresponding PR?

**Comment by harshkhandeparkar** [comment]
Closing this.
