### ISSUE TITLE
*/_index.md: Update needed

### ISSUE THREAD

**Issue by proffapt** [kossiitkgp/docs#55]
**Give references**

- `/_index.md`
- `/community/_index.md`
- `/events/_index.md`

**What is your question?**

Are `/community/_index.md` and `/events/_index.md` really needed according to the new file arrangement? 
And shall `/_index.md` be updated with current state of file structure having links to whatever is there documented and just mentioning other undocumented things, similarly for other `_index.md`s files if they really serve a purpose ?

**Tell us who you are**

Arpit Bhardwaj, CTM
Y'21.

**Comment by proffapt** [comment]
@sahil-shubham @rakaar @amrtachaurasia @rajivharlalka @Yureien ^^

**Comment by rakaar** [comment]
The purpose of `_index.md`s is that it contains content of the page - https://beta.kossiitkgp.org/docs
Yes, ideally _index.md should have list of files. But it is not updated. If you wish you can update it. But many things on the website need changes. I suggest we look at it later - sometime during vaccations.
